name = "efootball-cloudflare"
main = "src/index.js"
compatibility_date = "2024-11-01"

# Serve static assets from public folder
assets = { directory = "./public" }

[[durable_objects.bindings]]
name = "FOOTBALL_ROOM"
class_name = "FootballRoom"

[[migrations]]
tag = "v1"
new_classes = ["FootballRoom"]
