name = "multiplayer-particles"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "PARTICLE_ROOM"
class_name = "ParticleRoom"

[[migrations]]
tag = "v1"
new_classes = ["ParticleRoom"]
