name = "efootball-cloudflare"
main = "worker.js"
compatibility_date = "2024-11-01"

# Static assets served by the Worker fallback
send_metrics = false

[[durable_objects.bindings]]
name = "PARTICLE_ROOM"
class_name = "ParticleRoom"

[[migrations]]
tag = "v1"
new_classes = ["ParticleRoom"]
